---
  - name: Enable EPEL Repository on CentOS 8
    yum:
      name: epel-release
      state: present

  - name: Import EPEL GPG key.
    rpm_key:
      key: /etc/pki/rpm-gpg/RPM-GPG-KEY-EPEL-{{ ansible_distribution_major_version }}
      state: present

  - name: Refrescar cache paquets yum
    yum: update_cache=yes

  - name: Add MariaDB repository
    yum_repository:
      name: mariadb
      description: 'Mariadb repository'
      baseurl: http://yum.mariadb.org/10.0/centos7-amd64/
      gpgkey: https://yum.mariadb.org/RPM-GPG-KEY-MariaDB
      gpgcheck: yes

  - name: Install MariaDB-Galera-server, MariaDB-client, MYSQL-python and Galera
    yum:
      name: "{{ packages }}"
      update_cache: yes
      state: latest
    vars:
      packages:
       - mariadb-server-galera
       - mariadb-common
       - galera
       #- mysql-python
       
  - name: Add mysql port to the firewall
    firewalld:
     service: mysql
     zone: public
     permanent: true
     state: enabled
     immediate: true

  - name: Add tcp ports used by MySQL/MariaDB and Galera to the firewall
    firewalld:
      port: "{{ item }}"
      zone: public
      permanent: true
      state: enabled
      immediate: true
    with_items:
      - '3030/tcp'
      - '3306/tcp'
      - '4567/tcp'
      - '4568/tcp'
      - '4444/tcp'
      - '9000/tcp'
      - '9200/tcp'
      - '4567/udp'

  - name: Restart firewalld to have new rules take effect.
    service:
      name: firewalld
      state: restarted