---
  all:
    children:
      centos:
        children:
          apache:
            children:
              back:
                hosts:
                  back[1:3]:
              front:
                hosts:
                  front[1:3]:
          storage:            
            hosts:
              storage[1:3]:

          haproxy:            
            hosts:
              balancer[1:2]: