---
    - name: install nfs-utils
      yum: name=nfs-utils state=latest

    - name: install rpcbind
      yum: name=rpcbind state=latest


    - name: Create a mountable directory if it does not exist
      file:
        path: /mnt/exports/html_front
        state: directory
        owner: root
        group: root
        mode: '0777'

    - name: Create a mountable directory if it does not exist
      file:
        path: /mnt/exports/html_back
        state: directory
        owner: root
        group: root
        mode: '0777'

    - name: Create a mountable directory if it does not exist
      file:
        path: /mnt/exports/configs
        state: directory
        owner: root
        group: root
        mode: '0777'
   
    - name: Copy exports file.
      template:
        src: template/exports.j2
        dest: /etc/exports
        owner: root
        group: root
        mode: 0644


    - name: Open ports
      shell: sudo firewall-cmd --permanent --add-service=nfs

    - name: Open ports rpcbind
      shell: sudo firewall-cmd --permanent --add-service=rpc-bind

    - name: Open port mountd
      shell: sudo firewall-cmd --permanent --add-service=mountd

    - name: Reload firewall
      shell: sudo firewall-cmd --reload

    - name: NFS apply change configure
      shell: systemctl reload nfs;exportfs -a


    - name: start nfs-server.service
      service:
        name: nfs-server
        state: started
       
