---
  - name: install httpd
    dnf: name=httpd state=latest

  - name: Enable service
    service:
      name: httpd
      state: started

  - name: Create firewall rule for apache service
    firewalld:
      service: http
      zone: public
      permanent: yes
      immediate: yes
      state: enabled

  - name: Obrir port 80
    firewalld:
      zone: public
      port: 80/tcp
      permanent: true
      state: enabled

  - name: Obrir port 80
    firewalld:
      zone: internal
      port: 80/tcp
      permanent: true
      state: enabled

  - name: Obrir port 443
    firewalld:
      zone: public
      port: 443/tcp
      permanent: true
      state: enabled

  - name: Create directory
    file:
      path: /etc/httpd/sites-available
      state: directory

  - name: Create directory
    file:
      path: /etc/httpd/sites-enabled
      state: directory

  - name: Copiar config apache
    template:
      src: templates/httpd_conf.j2
      dest: /etc/httpd/conf/httpd.conf
      owner: root
      group: root
      mode: 0644

  - name: Reiniciar servei firewalld
    service:
     enabled: "yes"
     name: "firewalld"
     state: "restarted"

  #- name: Enable module rewrite
    #apache2_module:
      #state: present
      #name: rewrite

  #- name: Enable module xml2enc
    #apache2_module:
      #state: present
      #name: xml2enc

  #- name: Enable module ssl
    #apache2_module:
      #state: present
      #name: ssl

  #- name: Enable module headers
    #apache2_module:
      #state: present
      #name: headers

  - name: Copy php.ini
    template:
      src: templates/httpd_php.ini.j2
      dest: /etc/php.ini
      owner: root
      group: root
      mode: 0644

  - name: Restart apache service
    service:
      name: httpd
      state: restarted

  - name: Copy php.conf
    template:
      src: templates/php.conf.j2
      dest: /etc/httpd/conf.d/php.conf
      owner: root
      group: root
      mode: 0644