---
  - name: install nfs-utils
    yum: name=nfs-utils state=latest
  - name: install nfs4-acl-tools
    yum: name=nfs4-acl-tools state=latest

  - name: Create a mountable directory if it does not exist
    file:
      path: /var/www/configs
      state: directory
      owner: root
      group: root
      mode: '0777'

  - name: Open ports
    shell: sudo firewall-cmd --permanent --add-service=nfs

  - name: Open ports rpcbind
    shell: sudo firewall-cmd --permanent --add-service=rpc-bind

  - name: Open port mountd
    shell: sudo firewall-cmd --permanent --add-service=mountd

  - name: Reload firewall
    shell: sudo firewall-cmd --reload

  - name: Mount volumn
    shell: sudo mount {{ ip_nfs }}:/var/www/configs /var/www/configs

  - include: front.yml
    when:  front == "true"
  - include: back.yml
    when: back == "true"


